### ISSUE TITLE
Dude, Alternator and Volt in your NickARnH don't work, please fix it, NickARwH doesn't work either  

### ISSUE THREAD

**Issue by blbl777** [ansnw/Apex-AHK-script#1]
Dude, Alternator and Volt in your NickARnH don't work, please fix it, NickARwH doesn't work either  
Please, thank you  
Please forgive me for my poor English

**Comment by ansnw** [comment]
> Dude, Alternator and Volt in your NickARnH don't work, please fix it, NickARwH doesn't work either Please, thank you Please forgive me for my poor English

It should be working. At least it is working on my PC

**Comment by ansnw** [comment]
Try downloading the script again (I updated it 2 hours ago)
