### ISSUE TITLE
The new version makes the gun unusable.

### ISSUE THREAD

**Issue by blbl777** [ansnw/Apex-AHK-script#2]
The upgraded version doesn't fit all of my guns.   Excuse me, Sir, can you upload the previous version?   Thank you very much!   Because I accidentally replaced it, please

**Comment by blbl777** [comment]
Because I accidentally replaced it, please

**Comment by blbl777** [comment]
I didn't change any file Settings or game Settings. I first opened AHKHider and then NickARnH, but there was no effect. I was full game, 1920X1080.  I clearly can use the previous version, this version is not available.

**Comment by blbl777** [comment]
Replace the new icon with the old file and all guns will be available. I already have them, thank you

**Comment by ansnw** [comment]
I have no idea. I just uploaded the version I am currently using directly to GitHub. It works well for me.
